### ISSUE TITLE
Dynamic table generation.

### ISSUE THREAD

**Issue by robbert229** [antonheryanto/dapper-rainbow-mysql#2]
Would adding in dynamic table generation be a bad idea? I have already completed most of this but I am wondering if it is okay for me to continue to make pull requests.

**Comment by antonheryanto** [comment]
its not bad idea, i will look into it. but better to put its own class and can be used optionally. as imho I don't want this library to far different with upstream dapper-rainbow.

**Comment by robbert229** [comment]
That's fine, I am planning on testing it out here, and then making a pull request on the main repo.
