### ISSUE TITLE
Is it possible to also support attributes on properties

### ISSUE THREAD

**Issue by BrutalSimplicity** [antonheryanto/dapper-rainbow-mysql#6]
I'm not looking for anything overly verbose, but having a simple decorator on properties and classes should your database schema have different naming would be nice.

**Comment by antonheryanto** [comment]
table name to class mapping easy handle by changing your Database class property into the table name
where property mapping to column can be handle by shadow property, didn't time and motivation yet to  handle edge cases for that since there is simple workaround (which personally uses).

```csharp
class MyTableClass
{
  public MyProperty {get; set;}
  myDbProperty { set { MyProperty = value } }
}

class Db : Database<Db> 
{
  public Table<MyTableClass> MyTableName { get; set; }
}
```
