### ISSUE TITLE
Framework 4.0

### ISSUE THREAD

**Issue by martinslae** [antonheryanto/dapper-rainbow-mysql#7]
I need install on Windows XP  and I need complile in framework 4.0 fot this.

Dapper is able. 
Is able the Rainbow?

thanks

**Comment by antonheryanto** [comment]
current targeting 4.5 above, but its in my priority list to support net40 and netstandard 1.3

**Comment by antonheryanto** [comment]
add support for net40, net45, net46, netstandard 1.3 and netstandard 2.0 at [nuget](https://www.nuget.org/packages/Dapper.Rainbow.MySql) 0.9.2
but support for net40 might depend on new dapper version which drop support for net40
